inherit_from:
  - .rubocop_airbnb.yml

Rails:
  Enabled: true

Layout/LineLength:
  Max: 120
  Exclude:
    - 'spec/models/quiz_history_of_committed_file_spec.rb'

AllCops:
  Exclude:
    - 'bin/*'
    - 'config/**/*'
    - 'db/*'
    - 'db/**/*'
    - 'vendor/**/*'
    - 'spec/spec_helper.rb'
  NewCops: enable
